Arrays



In [3]:
import numpy

def arrays(arr):
    
    return(numpy.array(arr[::-1], float))


arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 5 4 6 4 5 2 2
[2. 2. 5. 4. 6. 4. 5. 1.]


Shape and Reshape

In [5]:
import numpy as np
print(np.array(input().split(),int).reshape(3,3))

1 2 3 4 5 6 9 8 7
[[1 2 3]
 [4 5 6]
 [9 8 7]]


Transpose and Flatten



In [10]:
import numpy as np
n, m = map(int, input().split())
array = np.array([input().strip().split() for _ in range(n)], int)
print (array.transpose())
print (array.flatten())

1 2
 4 5
[[4]
 [5]]
[4 5]


Concatenete

In [11]:
import numpy as np
a, b, c = map(int,input().split())
arrA = np.array([input().split() for _ in range(a)],int)
arrB = np.array([input().split() for _ in range(b)],int)
print(np.concatenate((arrA, arrB), axis = 0))

1 2 3
1 2 
 1 5
1 5
[[1 2]
 [1 5]
 [1 5]]


Zeroes and ones

In [7]:
import numpy as np
a = tuple(map(int,input().split()))
print(np.ones(a,int))
print(np.zeros(a,int))

3 3 3
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]


Eye and identity

In [8]:
import numpy as np
print(str(np.eye(*map(int,input().split()))).replace('1',' 1').replace('0',' 0'))

2 2
[[ 1.  0.]
 [ 0.  1.]]


Array Maths

In [15]:
import numpy as np
n, m = map(int, input().split())
a, b = (np.array([input().split() for _ in range(n)], dtype=int) for _ in range(2))
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a%b)
print(a**b)

1 2
 4 5
5 6
[[ 9 11]]
[[-1 -1]]
[[20 30]]
[[0.8        0.83333333]]
[[4 5]]
[[ 1024 15625]]


Floor,celit and rint

In [4]:
import numpy as np
np.set_printoptions(sign=' ')
m = np.array(input().split(),float)
print(np.floor(m))
print(np.ceil(m))
print(np.rint(m))

1.5 6 4 89 2.69 35.5 
[  1.   6.   4.  89.   2.  35.]
[  2.   6.   4.  89.   3.  36.]
[  2.   6.   4.  89.   3.  36.]


SUM and proud

In [1]:
import numpy as np
N, M = map(int, input().split())
A = np.array([input().split() for _ in range(N)],int) 
print(np.prod(np.sum(A,axis=0), axis=0))

2 2
1 2 
3 4
24


min and max

In [10]:
import numpy as np

n,m=map(int,input().split())

lista=[list(map(int,input().split())) for i in range(n)]

ar=np.array(lista)

print(max(np.min(ar,axis=1)))

4 2
2 5
4 6
7 98
4 5
7


Mean,Var,STD

In [2]:
import numpy as np
N,M = map(int,input().split())
A = np.array([input().split() for _ in range(N)], int)
print(A.mean(axis=1))
print(A.var(axis=0))
print(A.std())


2 6
4 8
7 9
[6. 8.]
[2.25 0.25]
1.8708286933869707


Dot and Cross

In [5]:
n=int(input())
a = np.array([input().split() for _ in range(n)],int)
b = np.array([input().split() for _ in range(n)],int)
m = np.dot(a,b)
print (m)

2
4 5
8 7
4 6
9 7
[[61 59]
 [95 97]]


inner and outer

In [7]:
import numpy as np
A = np.array(input().split(), int)
B = np.array(input().split(), int)
print(np.inner(A,B))
print(np.outer(A,B))





0 1
4 5
5
[[0 0]
 [4 5]]


Polynamials

In [8]:
import numpy as np
n = list(map(float,input().split()))
m = input()
print(np.polyval(n,int(m)))

1.2 1 3
5
38.0


Algebra

In [12]:
n=int(input())
A = np.array([input().split() for _ in range(n)],int)
print(round(np.linalg.det(A),2))

2 
4 8
9 8
-40.0
